name: religion_calendar_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  aries:
    path: packages/aries
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.10
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_analytics: ^10.9.0
  firebase_storage: ^11.7.1
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  flutter_facebook_auth: ^6.2.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  uuid: ^4.4.0
  hooks_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.8
  image: ^4.1.7
  flutter_hooks: ^0.20.5
  intl: any
  lottie: ^3.1.0
  share_plus: ^8.0.3
  url_launcher: ^6.2.6
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  full_calender: ^1.2.12
  intl_translation: ^0.20.0
  go_router: ^14.2.1
  go_router_builder: ^2.7.0
  flutter_native_splash: ^2.4.1
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.3
  collection: ^1.18.0
  rrule: ^0.2.16
  skeletonizer: ^1.4.2
  firebase_app_check: ^0.2.1+18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  melos: ^5.2.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
