name: religion_calendar_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"
dependencies:
  aries:
    path: packages/aries
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_analytics: ^11.3.5
  firebase_storage: ^12.3.6
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  uuid: ^4.4.0
  hooks_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_hooks: ^0.20.5
  intl: any
  lottie: ^3.1.0
  share_plus: ^10.1.2
  url_launcher: ^6.2.6
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  full_calender: ^1.2.12
  go_router: ^14.2.1
  go_router_builder: ^2.7.0
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  collection: ^1.18.0
  rrule: ^0.2.16
  skeletonizer: ^1.4.2
  firebase_app_check: ^0.3.1+6
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.2.1
  flutter_animate: ^4.5.2
  flutter_markdown: ^0.7.6+2
  flutter_lorem: ^2.0.0
  toggle_list: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  melos: ^6.2.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/app_icons/
    - assets/documents/
    - .env