// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const flavorSuffix = 'PROD';

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_OPTION_ANDROID_API_KEY_${flavorSuffix}']!,
    appId: dotenv.env['FIREBASE_OPTION_ANDROID_APP_API_${flavorSuffix}']!,
    messagingSenderId:
        dotenv.env['FIREBASE_OPTION_MESSAGING_SENDER_ID_${flavorSuffix}']!,
    projectId: dotenv.env['FIREBASE_OPTION_PROJECT_ID_${flavorSuffix}']!,
    storageBucket:
        dotenv.env['FIREBASE_OPTION_STORAGE_BUCKET_${flavorSuffix}']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_OPTION_IOS_API_KEY_${flavorSuffix}']!,
    appId: dotenv.env['FIREBASE_OPTION_IOS_APP_API_${flavorSuffix}']!,
    messagingSenderId:
        dotenv.env['FIREBASE_OPTION_MESSAGING_SENDER_ID_${flavorSuffix}']!,
    projectId: dotenv.env['FIREBASE_OPTION_PROJECT_ID_${flavorSuffix}']!,
    storageBucket:
        dotenv.env['FIREBASE_OPTION_STORAGE_BUCKET_${flavorSuffix}']!,
    iosBundleId: dotenv.env['FIREBASE_OPTION_IOS_BUNDLE_ID_${flavorSuffix}']!,
  );
}
